/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 rex.glb 
Author: Al-Deezel (https://sketchfab.com/Al-dezel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/high-detailed-dinosaur-animation-running-9eac6b96031f4cc4905c31624d018ed1
Title: high detailed dinosaur animation (running)
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Group } from "three";
import { AnyObject } from "three/examples/jsm/nodes/Nodes.js";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";

interface RexProps {
  anime: number;
  position: [number, number, number];
  scale: number;
  handlerAnimations: () => void;
}
interface gltfProps extends GLTF {
  nodes: AnyObject;
  materials: AnyObject;
}
export function Rex(props: RexProps): JSX.Element {
  const group = useRef<Group>(new Group());
  const { nodes, materials, animations } = useGLTF(
    "./src/scenes/rex/rex.glb"
  ) as gltfProps;

  const { actions, names } = useAnimations(animations, group);

  const { anime } = props;
  useEffect(() => {
    const actionTitle = names[anime];
    if (actionTitle) {
      const action = actions[actionTitle];
      if (action) {
        action.reset().fadeIn(0.5).play();
        // make smooth animations switch
        return () => action.fadeOut(0.5);
      }
    }
    return () => {};
  }, [actions, anime, names]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onClick={props.handlerAnimations}
    >
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.286}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_0" scale={0.01}>
                <group name="skeletal3_3">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="TRex2_2_correction">
                      <group name="TRex2_2" />
                    </group>
                    <skinnedMesh
                      castShadow
                      receiveShadow={true}
                      name="Object_80"
                      geometry={nodes.Object_80.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_80.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
useGLTF.preload("./src/scenes/rex/rex.glb");
export default Rex;
