/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 rex.glb 
Author: Al-Deezel (https://sketchfab.com/Al-dezel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/high-detailed-dinosaur-animation-running-9eac6b96031f4cc4905c31624d018ed1
Title: high detailed dinosaur animation (running)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Rex(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./src/scenes/rex/rex.glb");
  const { actions, names } = useAnimations(animations, group);

  const { anime } = props;
  useEffect(() => {
    // reset all animation, to can switch between them
    for (const name in actions) {
      actions[name].stop();
    }
    actions[names[anime]].reset().fadeIn(1).play();
  }, [actions, anime, names]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onClick={props.handlerAnimations}
    >
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.286}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_0" scale={0.01}>
                <group name="skeletal3_3">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="TRex2_2_correction">
                      <group name="TRex2_2" />
                    </group>
                    <skinnedMesh
                      name="Object_80"
                      geometry={nodes.Object_80.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_80.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
useGLTF.preload("./src/scenes/rex/rex.glb");
export default Rex;
